'use client'

import { FormEvent, useMemo, useState } from 'react'
import { Home, LogOut, Menu, Pencil, Plus, Search, ShieldCheck, Trash2, UserRound, Users, X } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Role = 'admin' | 'umat'
type Person = { id: number; No_KK: string; Nama_Lengkap: string; Nama_Baptis: string; Hubungan_Keluarga: string; Agama: string; Status_Perkawinan: string; Pendidikan_Terakhir: string; Pekerjaan: string; Profesi: string }

const seed: Person[] = [
  { id: 1, No_KK: '3273012301010001', Nama_Lengkap: 'Budi Santoso', Nama_Baptis: 'Thomas', Hubungan_Keluarga: 'Kepala Keluarga', Agama: 'Katolik', Status_Perkawinan: 'Menikah', Pendidikan_Terakhir: 'S1', Pekerjaan: 'Karyawan Swasta', Profesi: 'Manajer' },
  { id: 2, No_KK: '3273012301010001', Nama_Lengkap: 'Maria Santoso', Nama_Baptis: 'Maria', Hubungan_Keluarga: 'Istri', Agama: 'Katolik', Status_Perkawinan: 'Menikah', Pendidikan_Terakhir: 'SMA', Pekerjaan: 'Ibu Rumah Tangga', Profesi: '-' },
  { id: 3, No_KK: '3273012301010002', Nama_Lengkap: 'Andreas Wijaya', Nama_Baptis: 'Andreas', Hubungan_Keluarga: 'Kepala Keluarga', Agama: 'Katolik', Status_Perkawinan: 'Menikah', Pendidikan_Terakhir: 'SMA', Pekerjaan: 'Wiraswasta', Profesi: 'Pemilik Toko' },
  { id: 4, No_KK: '3273012301010002', Nama_Lengkap: 'Clara Wijaya', Nama_Baptis: 'Clara', Hubungan_Keluarga: 'Anak', Agama: 'Katolik', Status_Perkawinan: 'Belum Menikah', Pendidikan_Terakhir: 'S1', Pekerjaan: 'Mahasiswa', Profesi: '-' },
]

const blank = (): Omit<Person, 'id'> => ({ No_KK: '', Nama_Lengkap: '', Nama_Baptis: '', Hubungan_Keluarga: 'Kepala Keluarga', Agama: 'Katolik', Status_Perkawinan: 'Menikah', Pendidikan_Terakhir: 'SMA', Pekerjaan: '', Profesi: '' })
const fields: (keyof Omit<Person, 'id'>)[] = ['No_KK', 'Nama_Lengkap', 'Nama_Baptis', 'Hubungan_Keluarga', 'Agama', 'Status_Perkawinan', 'Pendidikan_Terakhir', 'Pekerjaan', 'Profesi']

export function SithomasDashboard({ logoUrl }: { logoUrl?: string }) {
  const [people, setPeople] = useState(seed)
  const [role, setRole] = useState<Role | null>(null)
  const [loginMode, setLoginMode] = useState<Role>('admin')
  const [credential, setCredential] = useState('')
  const [password, setPassword] = useState('')
  const [familyKK, setFamilyKK] = useState('3273012301010001')
  const [query, setQuery] = useState('')
  const [modal, setModal] = useState(false)
  const [editing, setEditing] = useState<Person | null>(null)
  const [form, setForm] = useState(blank())
  const [mobileNav, setMobileNav] = useState(false)

  const visible = useMemo(() => people.filter((person) => (role === 'admin' || person.No_KK === familyKK) && Object.values(person).join(' ').toLowerCase().includes(query.toLowerCase())), [people, role, familyKK, query])
  const families = new Set(people.map((person) => person.No_KK)).size

  function login(event: FormEvent) {
    event.preventDefault()
    if (loginMode === 'admin' && credential === 'admin' && password === 'admin123') setRole('admin')
    if (loginMode === 'umat' && /^\d{4}$/.test(credential.trim())) {
      const match = people.find((person) => person.No_KK.endsWith(credential))
      if (match) { setFamilyKK(match.No_KK); setRole('umat') }
    }
  }
  function openForm(person?: Person) { setEditing(person ?? null); if (person) { const { id: _id, ...values } = person; setForm(values) } else setForm(blank()); setModal(true) }
  function save(event: FormEvent) {
    event.preventDefault()
    if (!form.No_KK || !form.Nama_Lengkap) return
    if (editing) setPeople((current) => current.map((person) => person.id === editing.id ? { ...form, id: editing.id } : person))
    else setPeople((current) => [{ ...form, id: Date.now() }, ...current])
    setModal(false)
  }
  function remove(id: number) { if (window.confirm('Hapus data umat ini?')) setPeople((current) => current.filter((person) => person.id !== id)) }

  if (!role) return <Login logoUrl={logoUrl} mode={loginMode} setMode={(value) => { setLoginMode(value); setCredential(''); setPassword('') }} credential={credential} setCredential={setCredential} password={password} setPassword={setPassword} onSubmit={login} />

  return <main className="min-h-screen bg-background"><div className="flex min-h-screen">
    <aside className={`${mobileNav ? 'fixed inset-0 z-40 flex' : 'hidden'} w-72 shrink-0 flex-col border-r border-border bg-card md:relative md:flex`}>
      <div className="flex items-center justify-between px-6 py-7"><Brand logoUrl={logoUrl} /><button className="md:hidden" onClick={() => setMobileNav(false)} aria-label="Tutup menu"><X /></button></div>
      <nav className="flex flex-col gap-2 px-4"><button className="flex items-center gap-3 rounded-xl bg-primary px-4 py-3 text-left text-sm font-bold text-primary-foreground"><Home /> Ringkasan umat</button><button className="flex items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold text-muted-foreground"><Users /> Data keluarga</button><button className="flex items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold text-muted-foreground"><UserRound /> Data anggota</button></nav>
      <div className="mt-auto border-t border-border p-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-accent font-bold text-primary">{role === 'admin' ? 'AD' : 'KK'}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{role === 'admin' ? 'Admin Utama' : 'Kepala Keluarga'}</p><p className="text-xs text-muted-foreground">{role === 'admin' ? 'Akses semua data' : `KK ...${familyKK.slice(-4)}`}</p></div><button onClick={() => setRole(null)} aria-label="Keluar"><LogOut className="text-muted-foreground" /></button></div></div>
    </aside>
    <section className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-border bg-card px-5 py-4 md:px-8"><button className="md:hidden" onClick={() => setMobileNav(true)} aria-label="Buka menu"><Menu /></button><div className="hidden md:block"><p className="text-xs font-bold uppercase tracking-widest text-primary">{role === 'admin' ? 'Mode admin utama' : 'Mode kepala keluarga'}</p><h1 className="font-serif text-xl font-bold">Pendataan Umat</h1></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-sm font-bold">St. Thomas Stasi Sampangan</p><p className="text-xs text-muted-foreground">Data aktif</p></div><div className="grid size-10 place-items-center rounded-full bg-primary text-sm font-bold text-primary-foreground">{role === 'admin' ? 'A' : 'K'}</div></div></header>
      <div className="mx-auto max-w-7xl p-5 md:p-8"><div className="mb-8 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="mb-2 text-sm font-bold text-primary">Selamat datang di SITHOMAS</p><h2 className="font-serif text-3xl font-bold tracking-tight md:text-4xl">Pusat data umat yang terpercaya.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Kelola data keluarga dan anggota umat Lingkungan St. Thomas dengan rapi, aman, dan mudah digunakan.</p></div>{role === 'admin' && <Button onClick={() => openForm()} className="rounded-xl"><Plus data-icon="inline-start" /> Tambah umat</Button>}</div>
        <div className="grid gap-4 sm:grid-cols-3"><Stat label="Total umat" value={String(visible.length)} icon={Users} /><Stat label="Keluarga" value={String(families)} icon={Home} /><Stat label="Mode akses" value={role === 'admin' ? 'Admin' : 'Keluarga'} icon={ShieldCheck} /></div>
        <div className="mt-8 rounded-2xl border border-border bg-card shadow-sm"><div className="flex flex-col gap-4 border-b border-border p-5 md:flex-row md:items-center md:justify-between"><div><h3 className="font-serif text-xl font-bold">Data anggota umat</h3><p className="mt-1 text-sm text-muted-foreground">{role === 'admin' ? 'Seluruh data umat lingkungan' : `Data keluarga dengan KK ...${familyKK.slice(-4)}`}</p></div><div className="relative w-full md:w-72"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input aria-label="Cari data" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama atau No. KK" className="h-10 w-full rounded-xl border border-input bg-background pl-10 pr-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></div></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-muted text-xs uppercase tracking-wide text-muted-foreground"><tr>{['Nama lengkap', 'No. KK', 'Hubungan', 'Agama', 'Pendidikan', 'Pekerjaan', 'Aksi'].map((heading) => <th key={heading} className="px-5 py-4 font-bold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{visible.map((person) => <tr key={person.id} className="hover:bg-muted/40"><td className="px-5 py-4"><p className="font-bold">{person.Nama_Lengkap}</p><p className="text-xs text-muted-foreground">{person.Nama_Baptis || 'Belum diisi'}</p></td><td className="px-5 py-4 font-mono text-xs">{person.No_KK}</td><td className="px-5 py-4">{person.Hubungan_Keluarga}</td><td className="px-5 py-4">{person.Agama}</td><td className="px-5 py-4">{person.Pendidikan_Terakhir}</td><td className="px-5 py-4">{person.Pekerjaan || '-'}</td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={() => openForm(person)} className="grid size-9 place-items-center rounded-lg border border-border text-primary hover:bg-accent" aria-label={`Edit ${person.Nama_Lengkap}`}><Pencil /></button>{role === 'admin' && <button onClick={() => remove(person.id)} className="grid size-9 place-items-center rounded-lg border border-border text-destructive hover:bg-destructive/10" aria-label={`Hapus ${person.Nama_Lengkap}`}><Trash2 /></button>}</div></td></tr>)}</tbody></table>{visible.length === 0 && <p className="p-10 text-center text-sm text-muted-foreground">Data tidak ditemukan.</p>}</div></div>
      </div></section></div>{modal && <Modal editing={editing} form={form} setForm={setForm} onClose={() => setModal(false)} onSave={save} />}</main>
}

function Brand({ logoUrl }: { logoUrl?: string }) { const [failed, setFailed] = useState(false); return <div className="flex items-center gap-3"><div className="grid size-11 shrink-0 place-items-center overflow-hidden rounded-xl bg-primary text-primary-foreground">{logoUrl && !failed ? <img src={logoUrl} alt="" aria-hidden="true" className="size-full object-contain" onError={() => setFailed(true)} /> : <ShieldCheck />}</div><div><p className="font-serif text-xl font-bold">SITHOMAS</p><p className="text-[10px] uppercase tracking-[.18em] text-muted-foreground">St. Thomas Stasi</p></div></div> }
function Login({ logoUrl, mode, setMode, credential, setCredential, password, setPassword, onSubmit }: { logoUrl?: string; mode: Role; setMode: (value: Role) => void; credential: string; setCredential: (value: string) => void; password: string; setPassword: (value: string) => void; onSubmit: (event: FormEvent) => void }) { const [failed, setFailed] = useState(false); return <main className="grid min-h-screen place-items-center bg-background px-5 py-10"><div className="w-full max-w-md"><div className="mb-8 text-center"><div className="mx-auto mb-4 grid size-20 place-items-center overflow-hidden rounded-2xl bg-primary text-primary-foreground shadow-lg">{logoUrl && !failed ? <img src={logoUrl} alt="" aria-hidden="true" className="size-full object-contain" onError={() => setFailed(true)} /> : <ShieldCheck className="size-9" />}</div><p className="font-serif text-3xl font-bold">SITHOMAS</p><p className="mt-1 text-xs font-bold uppercase tracking-[.24em] text-primary">St. Thomas Stasi Sampangan</p></div><div className="rounded-3xl border border-border bg-card p-6 shadow-xl md:p-8"><h1 className="font-serif text-2xl font-bold">Masuk ke pendataan umat</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Pilih akses sesuai peran Anda.</p><div className="mt-6 grid grid-cols-2 rounded-xl bg-muted p-1"><button type="button" onClick={() => setMode('admin')} className={`rounded-lg py-2.5 text-sm font-bold ${mode === 'admin' ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`}>Admin utama</button><button type="button" onClick={() => setMode('umat')} className={`rounded-lg py-2.5 text-sm font-bold ${mode === 'umat' ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`}>Kepala keluarga</button></div><form onSubmit={onSubmit} className="mt-6 flex flex-col gap-4"><label className="flex flex-col gap-2 text-sm font-bold">{mode === 'admin' ? 'Username' : '4 angka terakhir No. KK'}<input required value={credential} onChange={(event) => setCredential(event.target.value)} inputMode="numeric" maxLength={mode === 'umat' ? 4 : 30} placeholder={mode === 'admin' ? 'admin' : '0001'} className="h-12 rounded-xl border border-input bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-ring" /></label>{mode === 'admin' && <label className="flex flex-col gap-2 text-sm font-bold">Kata sandi<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="admin123" className="h-12 rounded-xl border border-input bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-ring" /></label>}<Button type="submit" className="mt-2 h-12 rounded-xl text-base">Masuk</Button></form><p className="mt-5 text-center text-xs leading-5 text-muted-foreground">Admin: <b>admin</b> / <b>admin123</b><br />Kepala keluarga: gunakan 4 digit terakhir No. KK, contoh <b>0001</b></p></div></div></main> }
function Stat({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Users }) { return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="grid size-10 place-items-center rounded-xl bg-accent text-primary"><Icon /></div><p className="mt-5 text-sm text-muted-foreground">{label}</p><p className="mt-1 font-serif text-3xl font-bold">{value}</p></div> }
function Modal({ editing, form, setForm, onClose, onSave }: { editing: Person | null; form: Omit<Person, 'id'>; setForm: (value: Omit<Person, 'id'>) => void; onClose: () => void; onSave: (event: FormEvent) => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/50 p-4" role="dialog" aria-modal="true"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-border bg-card p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="font-serif text-2xl font-bold">{editing ? 'Edit data umat' : 'Tambah data umat'}</h2><p className="mt-1 text-sm text-muted-foreground">Lengkapi data umat Lingkungan St. Thomas.</p></div><button onClick={onClose} aria-label="Tutup"><X className="text-muted-foreground" /></button></div><form onSubmit={onSave} className="mt-6 grid gap-4 sm:grid-cols-2">{fields.map((field) => <label key={field} className="flex flex-col gap-2 text-sm font-bold">{field.replaceAll('_', ' ')}<input required={field === 'No_KK' || field === 'Nama_Lengkap'} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} className="h-11 rounded-xl border border-input bg-background px-3 font-normal capitalize outline-none focus:ring-2 focus:ring-ring" /></label>)}<div className="flex justify-end gap-3 sm:col-span-2"><Button type="button" variant="outline" onClick={onClose} className="rounded-xl">Batal</Button><Button type="submit" className="rounded-xl">Simpan data</Button></div></form></div></div> }
